ignore:
  - lib/pg_inspect/native.ex
  - lib/mix/tasks/benchmark.public_api.ex

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
