[tools]
erlang = "28.4"
elixir = "1.20.0-rc.3-otp-28"
ast-grep = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
rg = "latest"
sd = "latest"
yq = "latest"
zig = "0.15.2"
protoc = "latest"
