defmodule Mix.Tasks.Precompile.Checksum do
  use Mix.Task

  @shortdoc "Builds Zigler artifacts and writes checksum.exs"

  @moduledoc """
  Builds the Zigler precompiled artifacts for `PgInspect.Native.Binding` and
  writes their SHA256 sums to `checksum.exs`.

      mix precompile.checksum
      mix precompile.checksum --skip-precompile

  Use `--skip-precompile` to rewrite `checksum.exs` from the existing artifact
  files in `lib/pg_inspect/native/lib/` without rebuilding them.
  """

  @binding_file "lib/pg_inspect/native/binding.ex"
  @artifact_dir "lib/pg_inspect/native/lib"
  @checksum_file "checksum.exs"
  @module_prefix "Elixir.PgInspect.Native.Binding"

  @switches [skip_precompile: :boolean]

  @impl Mix.Task
  def run(args) do
    {opts, _argv, invalid} = OptionParser.parse(args, strict: @switches)

    case invalid do
      [] -> :ok
      _ -> Mix.raise("invalid options: #{format_invalid_options(invalid)}")
    end

    unless opts[:skip_precompile] do
      Mix.Task.reenable("zig.precompile")
      Mix.Task.run("zig.precompile", [@binding_file])
    end

    checksums = artifact_checksums()
    File.write!(@checksum_file, render_checksums(checksums))

    Mix.shell().info("Wrote #{length(checksums)} checksums to #{@checksum_file}")
  end

  defp artifact_checksums do
    version = Mix.Project.config()[:version] |> to_string()
    prefix = "#{@module_prefix}.#{version}."

    @artifact_dir
    |> Path.join("#{prefix}*")
    |> Path.wildcard()
    |> Enum.map(fn path -> {artifact_triple(path, prefix), artifact_sha(path)} end)
    |> Enum.sort_by(&elem(&1, 0))
    |> case do
      [] -> Mix.raise("no precompiled artifacts found in #{@artifact_dir}")
      entries -> entries
    end
  end

  defp artifact_triple(path, prefix) do
    path
    |> Path.basename()
    |> Path.rootname()
    |> String.replace_prefix(prefix, "")
  end

  defp artifact_sha(path) do
    path
    |> File.read!()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  defp render_checksums([]), do: "[]\n"

  defp render_checksums(entries) do
    body =
      Enum.map_join(entries, ",\n", fn {triple, sha} ->
        ~s(  {:"#{triple}", "#{sha}"})
      end)

    "# Generated by `mix precompile.checksum`.\n[\n#{body}\n]\n"
  end

  defp format_invalid_options(invalid) do
    invalid
    |> Enum.map(fn {option, _value} -> "--#{option}" end)
    |> Enum.join(", ")
  end
end
