defmodule Mix.Tasks.Precompile.ChecksumTest do
  use ExUnit.Case, async: false

  alias Mix.Tasks.Precompile.Checksum
  alias PgInspect.Native.Precompiled

  test "downloads release artifacts and writes checksums from fetched binaries" do
    tmp_dir =
      Path.join(System.tmp_dir!(), "precompile_checksum_#{System.unique_integer([:positive])}")

    artifact_dir = Path.join(tmp_dir, "artifacts")
    checksum_file = Path.join(tmp_dir, "checksum.exs")

    File.mkdir_p!(artifact_dir)

    File.write!(
      Path.join(artifact_dir, "#{Precompiled.artifact_prefix("0.1.0")}stale-linux-musl.so"),
      "stale"
    )

    on_exit(fn -> File.rm_rf!(tmp_dir) end)

    linux_name = "#{Precompiled.artifact_prefix("0.1.0")}x86_64-linux-gnu.so"
    macos_name = "#{Precompiled.artifact_prefix("0.1.0")}aarch64-macos-none.so"

    release = %{
      "assets" => [
        %{
          "name" => macos_name,
          "browser_download_url" => "https://downloads.example/macos",
          "url" => "https://api.github.com/assets/2"
        },
        %{
          "name" => linux_name,
          "browser_download_url" => "https://downloads.example/linux",
          "url" => "https://api.github.com/assets/1"
        },
        %{
          "name" => "notes.txt",
          "browser_download_url" => "https://downloads.example/notes",
          "url" => "https://api.github.com/assets/3"
        }
      ]
    }

    http_get = fn
      "https://api.github.com/repos/hlindset/pg_inspect/releases/tags/v0.1.0", _headers ->
        JSON.encode!(release)

      "https://downloads.example/linux", _headers ->
        "linux-binary"

      "https://downloads.example/macos", _headers ->
        "macos-binary"
    end

    Checksum.run_with(
      %{from_release: true},
      %{
        artifact_dir: artifact_dir,
        binding_file: "ignored",
        checksum_file: checksum_file,
        http_get: http_get,
        module_prefix: Precompiled.module_prefix(),
        release_repo: Precompiled.release_repo(),
        shell: Mix.Shell.Process,
        version: "0.1.0"
      }
    )

    assert File.read!(Path.join(artifact_dir, linux_name)) == "linux-binary"
    assert File.read!(Path.join(artifact_dir, macos_name)) == "macos-binary"

    refute File.exists?(
             Path.join(artifact_dir, "#{Precompiled.artifact_prefix("0.1.0")}stale-linux-musl.so")
           )

    assert File.read!(checksum_file) == """
           # Generated by `mix precompile.checksum`.
           [
             {:"aarch64-macos-none", "#{sha256("macos-binary")}"},
             {:"x86_64-linux-gnu", "#{sha256("linux-binary")}"}
           ]
           """
  end

  test "release url template is a binary suitable for Zigler web precompiles" do
    assert is_binary(Precompiled.release_url_template())
  end

  defp sha256(binary) do
    binary
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end
end
